name: Build Desktop App with Pake

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Pake
        run: npm install -g pake-cli

      - name: Build with Pake
        run: |
          # 根据你的需求修改这个URL和应用名称
          pake "https://your-website-url.com" --name "YourAppName" --icon ./app.iconset/icon_256x256.png --height 800 --width 1200 --transparent --fullscreen --resize --multi-arch --targets ${{ matrix.platform == 'macos-latest' && 'deb,appimage,rpm' || matrix.platform == 'ubuntu-20.04' && 'deb,appimage,rpm' || 'msi,nsis' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pake-app-${{ matrix.platform }}
          path: |
            dist/
            *.dmg
            *.deb
            *.rpm
            *.AppImage
            *.msi
            *.exe